
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './component/Navbar/Navbar'
import Footer from './component/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='grid place-items-center bg-white  '>
    <body className={`${inter.className} w-[1440px] bg-white border-2 border-red-500`}>
      <Navbar/>
        {children}
      <Footer/>
        </body>
      
    </html>
  )
}
